create table visits (
  id bigint generated by default as identity primary key,
  site_id text,
  kind text,
  url text,
  path text,
  referrer text,
  lang text,
  time_on_page_sec int,
  max_scroll int,
  country text,
  region text,
  city text,
  ts timestamptz default now()
);
